baseURL = "https://knrdl.github.io/"
languageCode = "en-us"
title = "knrdlog"
theme = "spaghetti"
enableGitInfo = true  # get lastmod date from git

copyright = """Licensed under <a href='https://creativecommons.org/publicdomain/zero/1.0/' target='_blank' rel='noopener norefferer'>CC0 1.0</a> |
<a href="https://gohugo.io" target='_blank' rel='noopener norefferer'>Hugo</a> theme inspired by <a href="https://github.com/vamc19" target='_blank' rel='noopener norefferer'>vamc19</a> |
 Hosted by <a href="https://pages.github.com" target='_blank' rel='noopener norefferer'>Github</a> (<a href="https://github.com/site/privacy" target='_blank' rel='noopener norefferer'>Privacy Policy</a>)
"""

[frontmatter]
lastmod = ['lastmod', ':git', 'date']

[params]
author = "knrdl"
description = "notes to self"

[taxonomies]
tag = 'tags'
lang = 'lang'

[markup]
[markup.highlight]
style = 'dracula'
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = "github"
url = "https://github.com/knrdl"
weight = 1

[[menu.main]]
name = "rss"
url = "/index.xml"
weight = 2
