flowchart TD
    Gis(GIS) -->|shows| Map(map)
    Map -->|has a| Proj(projection)
    Map -->|shows multiple| Layer(layer)
    Layer --> |is either a| Raster(raster layer)
    Layer --> |or is a| Vector(vector layer)
    Vector --> |consists of multiple| Feature(feature) 
    Feature --> |consists of multiple| TabAttr(tabular attribute)
    Feature --> |consists of one| GeomAttr(geometry attribute)
    GeomAttr --> |has| Style(style)
    Style --> |can have multiple| Symbol(symbol)
    Symbol --> Icon(shape/icon)
    Icon --> Size(size)
    Symbol --> Fill(fill)
    Fill --> FillColor(color)
    Stroke --> StrokeColor(color)
    Symbol --> Stroke(stroke)
    Stroke --> StrokeWidth(width)
    Style --> |can have multiple| Text(text/label)
    Icon --> SPlacement(placement)
    Text --> TPlacement(placement)
    Text --> TextColor(color)
    Text --> Font(font)
    Font --> FontSize(size)
    Font --> FontFamily(family)
    GeomAttr -->|has| Geom(geometry)
    Geom --> |is either a| BasicGeom{basic\ntypes}
    Geom --> |or is a| ComposedGeom{composed\ntypes}
    BasicGeom --> Point(point)
    BasicGeom --> LineString(line string)
    BasicGeom --> Polygon(polygon)
    Polygon -->|has special case| Circle(circle/ellipsoid)

    ComposedGeom --> MPoint(multi point)
    ComposedGeom --> MLineString(multi line string)
    ComposedGeom --> MPolygon(multi polygon)

